language: go
go:
 - 1.5
python:
 - 3.4
services:
 - couchdb
before_script:
 - curl -X PUT http://127.0.0.1:5984/_config/admins/adminuser -d '"password"'
script:
 - sleep 4s
 - cd scripts
 - ./setup.py localhost 5984 --user=adminuser --password=password --skip_master
 - sleep 4s
 - cd ..
 - cd users
 - go test -v ./...
 - sleep 2s
 - cd ../wikis
 - go test -v ./...
 - sleep 2s
 - cd ../notifications
 - go test -v ./...
 - sleep 2s
 - cd ../frontend
 - go test -v ./...
