language: go
go:
 - 1.3
 - 1.4
services:
 - couchdb
before_script:
 - curl -X PUT http://127.0.0.1:5984/_config/admins/adminuser -d '"password"' 
script:
 - go get github.com/twinj/uuid
 - go test -v ./...
